
logging:
  level:
    org.springframework.security : debug
    web: debug

spring:
  data:
    rest:
      base-path: /data-api
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
taco:
  orders:
    pageSize: 10