
logging:
  level:
#    org.springframework.security : debug
#    web: debug
    root: debug

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  data:
    rest:
      base-path: /data-api
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
taco:
  orders:
    pageSize: 10